plugins {
    kotlin("jvm") version "1.9.22"
    kotlin("plugin.serialization") version "1.9.22"
    id("org.openapi.generator") version "7.2.0"
}

group = "com.poketactics"
version = "1.0.0"

repositories {
    mavenCentral()
}

dependencies {
    val ktorVersion = "2.3.7"
    
    // Ktor core and client for Android/JVM
    implementation("io.ktor:ktor-client-core:$ktorVersion")
    implementation("io.ktor:ktor-client-cio:$ktorVersion") 
    
    // For client understanding JSON
    implementation("io.ktor:ktor-client-content-negotiation:$ktorVersion")
    implementation("io.ktor:ktor-serialization-kotlinx-json:$ktorVersion")
}

openApiGenerate {
    generatorName.set("kotlin")
    
    inputSpec.set("$projectDir/swagger.json") 
    outputDir.set("$projectDir")
    apiPackage.set("com.poketactics.clients.api")
    modelPackage.set("com.poketactics.clients.models")
    configOptions.set(mapOf(
        "library" to "jvm-ktor",
        "serializationLibrary" to "kotlinx_serialization",
        "enumPropertyNaming" to "UPPERCASE",
        "useCoroutines" to "true",
        "generatedAnnotations" to "true"
    ))
}

// Make Kotlin compilation depends on the swagger generation
tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile> {
    dependsOn("openApiGenerate")
}

// Add autogenerated directory to the project
sourceSets {
    main {
        kotlin.srcDir("${project.layout.buildDirectory.get()}/generated/src/main/kotlin")
    }
}