services:
  db:
    image: ${DB_IMAGE}
    container_name: poketactics_db
    restart: always
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    deploy:
      resources:
        limits:
          memory: 1024M
        reservations:
          memory: 128M

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: poketactics_api
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__DefaultConnection=server=db;database=${DB_NAME};user=${DB_USER};password=${DB_PASSWORD};
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_ENVIRONMENT=Development
    deploy:
      resources:
        limits:
          memory: 1024M
        reservations:
          memory: 128M

volumes:
  mysql_data: