name: .NET CI

on:
  push:
    branches: [ "develop", "main" ]
  pull_request:
    branches: [ "develop", "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.300
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Install SonarScanner
      run: dotnet tool install --global dotnet-sonarscanner
    - name: Sonar Begin
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        dotnet sonarscanner begin \
          /k:"oscsaez_poke-tactics-api" \
          /o:"oscsaez" \
          /d:sonar.host.url="https://sonarcloud.io" \
          /d:sonar.login="${SONAR_TOKEN}" \
          /d:sonar.cs.opencover.reportsPaths="**/TestResults/**/coverage.opencover.xml" \
          /d:sonar.coverage.exclusions="**/Entities/**,**/Models/**,**/DTOs/**,**/Migrations/**,**/*Program.cs*,**/*Startup.cs*, **/swagger.json, **/.openapi-generator-ignore, **/gradlew, **/gradlew.bat, **/com/poketactics/clients/api/**/*, **/com/poketactics/clients/models/**/*"
          /d:sonar.sources=".,PokeTactics.Api.Clients.Kotlin/src/main/kotlin" \
          /d:sonar.tests="PokeTactics.Api.Clients.Kotlin.Test/src/test/kotlin" \
          /d:sonar.junit.reportPaths="PokeTactics.Api.Clients.Kotlin.Test/build/test-results/test" \
          /d:sonar.kotlin.binaries="PokeTactics.Api.Clients.Kotlin/build/classes/kotlin/main"
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test with coverage
      env:
        DB_IMAGE: mysql:8.0
        DB_NAME: poketactics
        DB_USER: root
        DB_PASSWORD: password
      run: |
        dotnet test \
          --no-build \
          --verbosity normal \
          --collect:"XPlat Code Coverage" \
          -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
    - name: Client tests
      working-directory: ./PokeTactics.Api.Clients.Kotlin.Test
      run: ./gradlew test --no-daemon
    - name: Sonar End
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: dotnet sonarscanner end /d:sonar.login="${SONAR_TOKEN}"
