name: .NET CI

on:
  push:
    branches: [ "develop", "main" ]
  pull_request:
    branches: [ "develop", "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 3333:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.300
    - name: Install SonarScanner
      run: dotnet tool install --global dotnet-sonarscanner
    - name: Sonar Begin
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        dotnet sonarscanner begin \
          /k:"oscsaez_poke-tactics-api" \
          /o:"oscsaez" \
          /d:sonar.host.url="https://sonarcloud.io" \
          /d:sonar.login="${SONAR_TOKEN}" \
          /d:sonar.cs.opencover.reportsPaths="**/coverage.opencover.xml"
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test with coverage
      run: |
        dotnet test \
          --no-build \
          /p:CollectCoverage=true \
          /p:CoverletOutputFormat=opencover \
          /p:CoverletOutput=coverage/
    - name: Sonar End
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: dotnet sonarscanner end /d:sonar.login="${SONAR_TOKEN}"
